apiVersion: skaffold/v2beta6
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
      - ./infra/k8s-dev/*
build:
  local:
    useBuildkit: true
    concurrency: 0
    push: false
  artifacts:
    - image: ghcr.io/kchiu-dev/auth
      context: auth
      docker:
        dockerfile: Dockerfile
        buildArgs:
          CR_PAT: "{{.CR_PAT}}"
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: ghcr.io/kchiu-dev/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
        - src: '**/*.js'
          dest: .
    - image: ghcr.io/kchiu-dev/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
        buildArgs:
          CR_PAT: "{{.CR_PAT}}"
      sync:
        manual:
        - src: 'src/**/*.ts'
          dest: .
    - image: ghcr.io/kchiu-dev/orders
      context: orders
      docker:
        dockerfile: Dockerfile
        buildArgs:
          CR_PAT: "{{.CR_PAT}}"
      sync:
        manual:
        - src: 'src/**/*.ts'
          dest: .     
    - image: ghcr.io/kchiu-dev/expiration
      context: expiration
      docker:
        dockerfile: Dockerfile
        buildArgs:
          CR_PAT: "{{.CR_PAT}}"
      sync:
        manual:
        - src: 'src/**/*.ts'
          dest: .     
    - image: ghcr.io/kchiu-dev/payments
      context: payments
      docker:
        dockerfile: Dockerfile
        buildArgs:
          CR_PAT: "{{.CR_PAT}}"
      sync:
        manual:
        - src: 'src/**/*.ts'
          dest: .     