apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: okteto/client:buildTag
          env:
            - name: NEXT_PUBLIC_BASE_URL
              value: 'https://ticketing-app-kch-chiu.cloud.okteto.net'
            - name: NEXT_PUBLIC_STRIPE_PUB
              value: 'pk_test_PrpgBBthPrEe50LAS87tRRGk006VZx64SB'
          resources:
            requests:
              memory: '300Mi'
              cpu: '200m'
            limits:
              memory: '600Mi'
              cpu: '300m'
---
apiVersion: v1
kind: Service
metadata:
  name: client-srv
spec:
  selector:
    app: client
  ports:
    - name: client
      protocol: TCP
      port: 3000
      targetPort: 3000
