apiVersion: apps/v1
kind: Deployment
metadata:
  name: expiration-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expiration
  template:
    metadata:
      labels:
        app: expiration
    spec:
      containers:
        - name: expiration
          image: okteto/expiration:buildTag
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              valueFrom:
                configMapRef:
                  name: nats-url
                  key: nats-url
            - name: NATS_CLUSTER_ID
              valueFrom:
                configMapRef:
                  name: nats-cluster-id
                  key: nats-cluster-id
            - name: REDIS_HOST
              value: expiration-redis-srv
          resources:
            requests:
              memory: '300Mi'
              cpu: '200m'
            limits:
              memory: '600Mi'
              cpu: '300m'