apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: okteto/gateway:buildTag
          env:
            - name: APOLLO_KEY
              valueFrom:
                secretKeyRef:
                  name: ticketing-gateway-key
                  key: ticketing-gateway-key
            - name: APOLLO_GRAPH_REF
              valueFrom:
                configMapKeyRef:
                  name: gateway-config
                  key: apollo-graph-ref
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: gateway-config
                  key: node-env
          resources:
            requests:
              memory: '400Mi'
              cpu: '200m'
            limits:
              memory: '800Mi'
              cpu: '400m'
  strategy:
    type: Recreate
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-srv
spec:
  selector:
    app: gateway
  ports:
    - name: gateway
      protocol: TCP
      port: 4000
      targetPort: 4000
    