apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ticketing-app
  annotations:
    dev.okteto.com/generate-host: "true"
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - http:
        paths:
          - path: /api/tickets
            backend:
              serviceName: tickets-srv
              servicePort: 3000
          - path: /api/gateway
            backend:
              serviceName: gateway-srv
              servicePort: 4000
          - path: /
            backend:
              serviceName: client-srv
              servicePort: 3000