apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ticketing-app
  annotations:
    kubernetes.io/ingress.class: "nginx"
    dev.okteto.com/generate-host: "true"
spec:
  rules:
    - http:
        paths:
          - path: /api/gateway/graphql
            backend:
              serviceName: gateway-srv
              servicePort: 4000
          - path: /
            backend:
              serviceName: client-srv
              servicePort: 3000