apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - client-depl.yml
  - expiration-depl.yml
  - expiration-redis-depl.yml
  - nats-depl.yml
  - orders-depl.yml
  - orders-mongo-depl.yml
  - payments-depl.yml
  - payments-mongo-depl.yml
  - tickets-depl.yml
  - tickets-mongo-depl.yml
  - ingress-srv.yml

configMapGenerator:
  - name: client-config
    literals:
      - nextauth-url=https://ticketing-app-kch-chiu.cloud.okteto.net
      - nextauth-url-internal=http://client-srv:3000
      - github-client-id=d003635d4feaa49c2253
      - client-payments-relativeurl=/api/payments
      - client-tickets-relativeurl=/api/tickets
      - client-orders-relativeurl=/api/orders
      - client-stripe-pub=pk_test_51FTiiHFzQH4GYdNSelC82u5p5X10AOC8sglP6ePVWcCy4v376diHYPDPvay5Y5M6m7qCqXOHRKwsjTpaL1baKbhB00VwJrOImM
  - name: nats-config
    literals:
      - nats-url=http://nats-srv:4222
      - nats-cluster-id=ticketing
  - name: mongo-config
    literals:
      - mongo-orders-uri=mongodb://orders-mongo-srv:27017/orders
      - mongo-payments-uri=mongodb://payments-mongo-srv:27017/payments
      - mongo-tickets-uri=mongodb://tickets-mongo-srv:27017/tickets
  - name: redis-config
    literals:
      - redis-expiration-host=expiration-redis-srv

secretGenerator:
  - name: github-client-secret
    literals:
      - github-client-secret=$GITHUB_CLIENT_SECRET
  - name: jwt-secret
    literals:
      - jwt-secret=$JWT_SECRET
  - name: stripe-secret
    literals:
      - stripe-secret=$STRIPE_SECRET

generatorOptions:
  disableNameSuffixHash: true
