apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - tickets-depl.yml
  - orders-depl.yml
  - dgraph-single.yml
  - ingress-srv.yml
  - gateway-depl.yml

configMapGenerator:
  - name: client-config
    literals:
      - nextauth-url=https://ticketing-app-kch-chiu.cloud.okteto.net
      - nextauth-url-internal=http://client-srv:3000
      - github-client-id=d003635d4feaa49c2253
      - client-payments-relativeurl=/api/payments
      - client-tickets-relativeurl=/api/tickets
      - client-orders-relativeurl=/api/orders
      - client-stripe-pub=pk_test_51FTiiHFzQH4GYdNSelC82u5p5X10AOC8sglP6ePVWcCy4v376diHYPDPvay5Y5M6m7qCqXOHRKwsjTpaL1baKbhB00VwJrOImM
  - name: gateway-config
    literals:
      - node-env=production
  - name: dgraph-config
    literals:
      - dgraph-uri=http://dgraph-public:8080
      - dgraph-alpha-security="whitelist=10.1.0.0:10.10.0.0"

secretGenerator:
  - name: github-client-secret
    literals:
      - github-client-secret=$GITHUB_CLIENT_SECRET
  - name: jwt-key
    literals:
      - jwt-key=$JWT_KEY
  - name: stripe-key
    literals:
      - stripe-key=$STRIPE_KEY
  - name: apollo-key
    literals:
      - apollo-key=$APOLLO_KEY

generatorOptions:
  disableNameSuffixHash: true
