apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - auth-depl.yml
  - auth-mongo-depl.yml
  - client-depl.yml
  - expiration-depl.yml
  - expiration-redis-depl.yml
  - nats-depl.yml
  - orders-depl.yml
  - orders-mongo-depl.yml
  - payments-depl.yml
  - payments-mongo-depl.yml
  - tickets-depl.yml
  - tickets-mongo-depl.yml
  - ingress-srv.yml

configMapGenerator:
- name: client-config
  literals:
  - client-payments-relativeurl=/api/payments/
  - client-auth-baseurl=http://auth-srv:3000
  - client-auth-relativeurl=/api/users/
  - client-tickets-baseurl=http://tickets-srv:3000
  - client-tickets-relativeurl=/api/tickets/
  - client-orders-baseurl=http://orders-srv:3000
  - client-orders-relativeurl=/api/orders/
  - client-stripe-pub=pk_test_PrpgBBthPrEe50LAS87tRRGk006VZx64SB
- name: nats-config
  literals:
  - nats-url=http://nats-srv:4222
  - nats-cluster-id=ticketing
- name: mongo-config
  literals:
  - mongo-auth-uri=mongodb://auth-mongo-srv:27017/auth
  - mongo-orders-uri=mongodb://orders-mongo-srv:27017/orders
  - mongo-payments-uri=mongodb://payments-mongo-srv:27017/payments
  - mongo-tickets-uri=mongodb://tickets-mongo-srv:27017/tickets
- name: redis-config
  literals:
  - redis-expiration-host=expiration-redis-srv

secretGenerator:
- name: jwt-secret
  literals:
  - jwt-secret=$JWT_SECRET
- name: stripe-secret
  literals:
  - stripe-secret=$STRIPE_SECRET

generatorOptions:
  disableNameSuffixHash: true
