apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-mongo-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders-mongo
  template:
    metadata:
      labels:
        app: orders-mongo
    spec:
      volumes:
        - name: orders-mongo-volume
          persistentVolumeClaim:
            claimName: orders-mongo-volume-claim
      containers:
        - name: orders-mongo
          image: mongo
          volumeMounts:
            - mountPath: '/data/db'
              name: orders-mongo-volume
          resources:
            requests:
              memory: '250Mi'
              cpu: '125m'
            limits:
              memory: '500Mi'
              cpu: '250m'
  strategy:
    type: Recreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: orders-mongo-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: orders-mongo-srv
spec:
  selector:
    app: orders-mongo
  ports:
    - name: db
      protocol: TCP
      port: 27017
      targetPort: 27017