apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
    spec:
      volumes:
        - name: payments-volume
          persistentVolumeClaim:
            claimName: payments-volume-claim
      containers:
        - name: payments
          image: okteto/payments:buildTag
          volumeMounts:
            - mountPath: '/data/node_modules'
              name: payments-volume
          env:
            - name: MONGO_URI
              valueFrom:
                configMapKeyRef:
                  name: mongo-config
                  key: mongo-payments-uri
            - name: STRIPE_KEY
              valueFrom:
                secretKeyRef:
                  name: stripe-secret
                  key: stripe-secret
          resources:
            requests:
              memory: '250Mi'
              cpu: '125m'
            limits:
              memory: '500Mi'
              cpu: '250m'
  strategy:
    type: Recreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: payments-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi    
---
apiVersion: v1
kind: Service
metadata:
  name: payments-srv
spec:
  selector:
    app: payments
  ports:
    - name: payments
      protocol: TCP
      port: 4003
      targetPort: 4003
