apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
    spec:
      containers:
        - name: payments
          image: okteto/payments:buildTag
          env:
            - name: GATEWAY_DGRAPH_URL
              valueFrom:
                configMapKeyRef:
                  name: gateway-dgraph-config
                  key: gateway-dgraph-url
            - name: STRIPE_KEY
              valueFrom:
                secretKeyRef:
                  name: stripe-key
                  key: stripe-key
            - name: STRIPE_API_VERISON
              valueFrom:
                configMapKeyRef:
                  name: payments-config
                  key: stripe-api-version
            - name: STRIPE_PAYMENT_METHOD_TYPE
              valueFrom:
                configMapKeyRef:
                  name: payments-config
                  key: stripe-payment-method-type
            - name: STRIPE_CURRENCY
              valueFrom:
                configMapKeyRef:
                  name: payments-config
                  key: stripe-currency
            - name: STRIPE_MODE
              valueFrom:
                configMapKeyRef:
                  name: payments-config
                  key: stripe-mode
            - name: STRIPE_CALLBACK_URL
              valueFrom:
                configMapKeyRef:
                  name: payments-config
                  key: stripe-callback-url
            - name: STRIPE_CALLBACK_URL_SUCCESS
              valueFrom:
                configMapKeyRef:
                  name: payments-config
                  key: stripe-callback-url-success
            - name: STRIPE_CALLBACK_URL_CANCEL
              valueFrom:
                configMapKeyRef:
                  name: payments-config
                  key: stripe-callback-url-cancel
          resources:
            requests:
              memory: '125Mi'
              cpu: '100m'
            limits:
              memory: '250Mi'
              cpu: '200m'
  strategy:
    type: Recreate
---
apiVersion: v1
kind: Service
metadata:
  name: payments-srv
spec:
  selector:
    app: payments
  ports:
    - name: payments
      protocol: TCP
      port: 4003
      targetPort: 4003
