apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
    spec:
      containers:
        - name: payments
          image: okteto/payments:buildTag
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              valueFrom:
                configMapKeyRef:
                  name: nats-config
                  key: nats-url
            - name: NATS_CLUSTER_ID
              valueFrom:
                configMapKeyRef:
                  name: nats-config
                  key: nats-cluster-id
            - name: MONGO_URI
              valueFrom:
                configMapKeyRef:
                  name: mongo-config
                  key: mongo-payments-uri
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: jwt-secret
            - name: STRIPE_KEY
              valueFrom:
                secretKeyRef:
                  name: stripe-secret
                  key: stripe-secret
          resources:
            requests:
              memory: '200Mi'
              cpu: '100m'
            limits:
              memory: '400Mi'
              cpu: '200m'
---
apiVersion: v1
kind: Service
metadata:
  name: payments-srv
spec:
  selector:
    app: payments
  ports:
    - name: payments
      protocol: TCP
      port: 3000
      targetPort: 3000
