apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickets-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tickets
  template:
    metadata:
      labels:
        app: tickets
    spec:
      containers:
        - name: tickets
          image: okteto/tickets:buildTag
          env:
            - name: NEXTAUTH_URL
              valueFrom:
                configMapKeyRef:
                  name: client-config
                  key: nextauth-url
            - name: NEXTAUTH_URL_INTERVAL
              valueFrom:
                configMapKeyRef:
                  name: client-config
                  key: nextauth-url-internal          
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              valueFrom:
                configMapKeyRef:
                  name: nats-config
                  key: nats-url
            - name: NATS_CLUSTER_ID
              valueFrom:
                configMapKeyRef:
                  name: nats-config
                  key: nats-cluster-id
            - name: MONGO_URI
              valueFrom:
                configMapKeyRef:
                  name: mongo-config
                  key: mongo-tickets-uri
          resources:
            requests:
              memory: '250Mi'
              cpu: '125m'
            limits:
              memory: '500Mi'
              cpu: '250m'
  strategy:
    type: Recreate
---
apiVersion: v1
kind: Service
metadata:
  name: tickets-srv
spec:
  selector:
    app: tickets
  ports:
    - name: tickets
      protocol: TCP
      port: 3000
      targetPort: 3000
