apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickets-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tickets
  template:
    metadata:
      labels:
        app: tickets
    spec:
      volumes:
        - name: tickets-volume
          persistentVolumeClaim:
            claimName: tickets-volume-claim
      containers:
        - name: tickets
          image: okteto/tickets:buildTag
          volumeMounts:
            - mountPath: '/data/node_modules'
              name: tickets-volume
          env:
            - name: MONGO_URI
              valueFrom:
                configMapKeyRef:
                  name: mongo-config
                  key: mongo-tickets-uri
          resources:
            requests:
              memory: '250Mi'
              cpu: '125m'
            limits:
              memory: '500Mi'
              cpu: '250m'
  strategy:
    type: Recreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tickets-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: tickets-srv
spec:
  selector:
    app: tickets
  ports:
    - name: tickets
      protocol: TCP
      port: 4001
      targetPort: 4001
