apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickets-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tickets
  template:
    metadata:
      labels:
        app: tickets
    spec:
      containers:
        - name: tickets
          image: okteto/tickets:buildTag
          env:
            - name: DGRAPH_URI
              valueFrom:
                configMapKeyRef:
                  name: dgraph-config
                  key: dgraph-uri
          resources:
            requests:
              memory: '125Mi'
              cpu: '100m'
            limits:
              memory: '250Mi'
              cpu: '200m'
      initContainers:
        - name: tickets-wait-for-dgraph
          image: curlimages/curl:latest
          command:
            - /bin/sh
            - -c
          args:
            - |
              echo Starting to wait for Dgraph to run
              while [ $(curl -w %{response_code} http://dgraph-public:8080 -o /dev/null) -ne 200 ]
              do
                echo Waiting for Dgraph to run...
                sleep 5
              done
              echo Dgraph is running
              echo Upload schema to Dgraph
              echo The current path is $(pwd)
              echo The current directory is $(ls)
              curl -X POST http://dgraph-public:8080/admin/schema --data-binary '@src/dgraph/dgraph-schema.graphql'
          resources:
            requests:
              memory: '125Mi'
              cpu: '100m'
            limits:
              memory: '250Mi'
              cpu: '200m'
  strategy:
    type: Recreate
---
apiVersion: v1
kind: Service
metadata:
  name: tickets-srv
spec:
  selector:
    app: tickets
  ports:
    - name: tickets
      protocol: TCP
      port: 4001
      targetPort: 4001
