apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-depl
  namespace: ingress-basic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: ghcr.io/kchiu-dev/client
          env:
            - name: NEXT_PUBLIC_STRIPE_PUB
              valueFrom:
                secretKeyRef:
                  name: stripe-pub
                  key: STRIPE_PUB
            - name: NEXT_PUBLIC_ENV
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: ENV
      imagePullSecrets:
        - name: ghcr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: client-srv
  namespace: ingress-basic
spec:
  selector:
    app: client
  ports:
    - name: client
      protocol: TCP
      port: 3000
      targetPort: 3000
