apiVersion: apps/v1
kind: Deployment
metadata:
  name: common-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: common
  template:
    metadata:
      labels:
        app: common
    spec:
      containers:
        - name: common
          image: ghcr.io/kchiu-dev/common
      imagePullSecrets:
        - name: acr-secret