apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: localhost:5000/client
          env:
            - name: NEXT_PUBLIC_STRIPE_PUB
              valueFrom: 
                secretKeyRef:
                  name: stripe-pub
                  key: stripe-pub
            - name: NEXT_PUBLIC_ENV
              valueFrom: 
                configMapKeyRef:
                  name: env-config
                  key: ENV
          ports:
            - containerPort: 9001   # run the container
            - containerPort: 7001   # debug the container
---
apiVersion: v1
kind: Service
metadata:
  name: client-srv
spec:
  selector:
    app: client
  ports:
    - name: client
      protocol: TCP
      port: 3000
      targetPort: 3000
