name: deploy-auth

on:
  push:
    branches: 
      - master
    paths:
      - 'auth/**'
        
jobs:
  build:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v2
     - run: docker login $DOCKER_ACRNAME --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
     - run: cd auth && docker build -t ${DOCKER_ACRNAME}/auth .  
     - run: docker push ${DOCKER_ACRNAME}/auth
       env:
         DOCKER_ACRNAME: ${{ secrets.DOCKER_ACRNAME }}
         DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
         DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
