name: preview-closed

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: Login
        uses: okteto/login@master
        with:
          token: ${{ secrets.OKTETO_TOKEN }}

      - name: Destroy the pipeline
        uses: okteto/destroy-pipeline@master
        with:
          namespace: kch-chiu
