name: preview

on: workflow_dispatch

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: Login
        uses: okteto/login@master
        with:
          token: ${{ secrets.OKTETO_TOKEN }}

      - name: Activate Namespace
        uses: okteto/namespace@master
        with:
          name: kch-chiu

      - name: Trigger the pipeline
        uses: okteto/pipeline@master
        with:
          timeout: 10m

      - name: Register Dgraph schemas
        run: |
          TICKETS_POD=$(kubectl get pod -l app=tickets -o jsonpath="{.items[0].metadata.name}")
          ORDERS_POD=$(kubectl get pod -l app=orders -o jsonpath="{.items[0].metadata.name}")
          kubectl exec $TICKETS_POD -- curl -sX POST http://dgraph-public:8080/admin/schema \
            --data-binary @src/dgraph/dgraph-schema.graphql
          kubectl exec $ORDERS_POD -- curl -sX POST http://dgraph-public:8080/admin/schema \
            --data-binary @src/dgraph/dgraph-schema.graphql

      - name: Register GraphQL API schemas
        env:
          APOLLO_KEY: ${{ secrets.APOLLO_KEY }}
        run: |
          npx apollo service:push \
            --graph=gateway-ticketing-graph \
            --serviceName=tickets \
            --serviceURL=http://tickets-srv:4001/graphql \
            --localSchemaFile=tickets/src/graphql/schema.graphql
          npx apollo service:push \
            --graph=gateway-ticketing-graph \
            --serviceName=orders \
            --serviceURL=http://orders-srv:4002/graphql \
            --localSchemaFile=orders/src/graphql/schema.graphql