name: preview

on: workflow_dispatch

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
        with:
          version: v0.6.0

      # - name: Cache Docker layers
      #   uses: actions/cache@v2
      #   with:
      #     path: /tmp/.buildx-cache
      #     key: ${{ runner.os }}-buildx-${{ github.sha }}
      #     restore-keys: |
      #       ${{ runner.os }}-buildx

      - name: Login to Okteto Registry
        uses: docker/login-action@v1
        with:
          registry: registry.cloud.okteto.net
          username: kch-chiu
          password: ${{ secrets.OKTETO_TOKEN }}

      - name: Build and push tickets
        uses: docker/build-push-action@v2
        with:
          context: tickets
          file: tickets/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          build-args: NODE_AUTH_TOKEN=${{ github.token }}
          push: true
          tags: registry.cloud.okteto.net/kch-chiu/tickets:latest
          #cache-from: type=local,src=/tmp/.buildx-cache
          #cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
          cache-from: type=gha, scope=${{ github.workflow }}
          cache-to: type=gha, scope=${{ github.workflow }}

      - name: Build and push orders
        uses: docker/build-push-action@v2
        with:
          context: orders
          file: orders/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          build-args: NODE_AUTH_TOKEN=${{ github.token }}
          push: true
          tags: registry.cloud.okteto.net/kch-chiu/orders:latest
          # cache-from: type=local,src=/tmp/.buildx-cache
          # cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
          cache-from: type=gha, scope=${{ github.workflow }}
          cache-to: type=gha, scope=${{ github.workflow }}
          
      - name: Build and push payments
        uses: docker/build-push-action@v2
        with:
          context: payments
          file: payments/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          build-args: NODE_AUTH_TOKEN=${{ github.token }}
          push: true
          tags: registry.cloud.okteto.net/kch-chiu/payments:latest
          # cache-from: type=local,src=/tmp/.buildx-cache
          # cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
          cache-from: type=gha, scope=${{ github.workflow }}
          cache-to: type=gha, scope=${{ github.workflow }}

      - name: Build and push gateway
        uses: docker/build-push-action@v2
        with:
          context: gateway
          file: gateway/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          build-args: NODE_AUTH_TOKEN=${{ github.token }}
          push: true
          tags: registry.cloud.okteto.net/kch-chiu/gateway:latest
          # cache-from: type=local,src=/tmp/.buildx-cache
          # cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
          cache-from: type=gha, scope=${{ github.workflow }}
          cache-to: type=gha, scope=${{ github.workflow }}

      - name: Build and push gateway-dgraph
        uses: docker/build-push-action@v2
        with:
          context: gateway-dgraph
          file: gateway-dgraph/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          build-args: NODE_AUTH_TOKEN=${{ github.token }}
          push: true
          tags: registry.cloud.okteto.net/kch-chiu/gateway-dgraph:latest
          # cache-from: type=local,src=/tmp/.buildx-cache
          # cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
          cache-from: type=gha, scope=${{ github.workflow }}
          cache-to: type=gha, scope=${{ github.workflow }}

      # - name: Move cache
      #   run: |
      #     rm -rf /tmp/.buildx-cache
      #     mv /tmp/.buildx-cache-new /tmp/.buildx-cache
          
      - name: Login to Okteto Cloud
        uses: okteto/login@master
        with:
          token: ${{ secrets.OKTETO_TOKEN }}

      - name: Activate Namespace
        uses: okteto/namespace@master
        with:
          namespace: kch-chiu

      - name: Trigger the pipeline
        uses: okteto/pipeline@master
        with:
          name: ${{ github.workflow }}
          timeout: 10m

      - name: Publish GraphQL Dgraph schema
        env:
          APOLLO_KEY: ${{ secrets.TICKETING_GATEWAY_DGRAPH_KEY }}
        run: |
          npx -p @apollo/rover \
            rover subgraph publish ticketing-gateway-dgraph-ex1l5e \
            --routing-url http://dgraph-srv:8080/graphql \
            --schema dgraph/schema.graphql \
            --name dgraph \
            --convert

      - name: Publish GraphQL API schemas
        env:
          APOLLO_KEY: ${{ secrets.TICKETING_GATEWAY_KEY }}
        run: |
          npx -p @apollo/rover \
            rover subgraph publish ticketing-gateway \
            --routing-url http://tickets-srv:4001/graphql \
            --schema tickets/src/graphql/schema.graphql \
            --name tickets \
            --convert
          npx -p @apollo/rover \
            rover subgraph publish ticketing-gateway \
            --routing-url http://orders-srv:4002/graphql \
            --schema orders/src/graphql/schema.graphql \
            --name orders \
            --convert
          npx -p @apollo/rover \
            rover subgraph publish ticketing-gateway \
            --routing-url http://payments-srv:4003/graphql \
            --schema payments/src/graphql/schema.graphql \
            --name payments \
            --convert