name: preview

on: workflow_dispatch

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Okteto Registry
        uses: docker/login-action@v1
        with:
          registry: registry.cloud.okteto.net
          username: kch-chiu
          password: ${{ secrets.OKTETO_TOKEN }}

      - name: Login to Okteto Cloud
        uses: okteto/login@master
        with:
          token: ${{ secrets.OKTETO_TOKEN }}

      - name: Activate Namespace
        uses: okteto/namespace@master
        with:
          namespace: kch-chiu

      - name: Build and push tickiets
        uses: docker/build-push-action@v2
        with:
          tags: registry.cloud.okteto.net/kch-chiu/tickets:${GITHUB_SHA}
          build-args: NODE_AUTH_TOKEN=${GITHUB_TOKEN}
          file: tickets/Dockerfile
          push: true

      - name: Build and push orders
        uses: docker/build-push-action@v2
        with:
          tags: registry.cloud.okteto.net/kch-chiu/orders:${GITHUB_SHA}
          build-args: NODE_AUTH_TOKEN=${GITHUB_TOKEN}
          file: orders/Dockerfile
          push: true

      - name: Build and push payments
        uses: docker/build-push-action@v2
        with:
          tags: registry.cloud.okteto.net/kch-chiu/payments:${GITHUB_SHA}
          build-args: NODE_AUTH_TOKEN=${GITHUB_TOKEN}
          file: payments/Dockerfile
          push: true

      - name: Build and push gateway
        uses: docker/build-push-action@v2
        with:
          tags: registry.cloud.okteto.net/kch-chiu/gateway:${GITHUB_SHA}
          build-args: NODE_AUTH_TOKEN=${GITHUB_TOKEN}
          file: gateway/Dockerfile
          push: true

      - name: Build and push gateway-dgraph
        uses: docker/build-push-action@v2
        with:
          tags: registry.cloud.okteto.net/kch-chiu/gateway-dgraph:${GITHUB_TOKEN}
          build-args: NODE_AUTH_TOKEN=${GITHUB_TOKEN}
          file: gateway-dgraph/Dockerfile
          push: true

      - name: Trigger the pipeline
        uses: okteto/pipeline@master
        with:
          name: $GITHUB_WORKFLOW
          timeout: 10m

      - name: Publish GraphQL Dgraph schema
        env:
          APOLLO_KEY: ${{ secrets.TICKETING_GATEWAY_DGRAPH_KEY }}
        run: |
          npx -p @apollo/rover \
            rover subgraph publish ticketing-gateway-dgraph-ex1l5e \
            --routing-url http://dgraph-srv:8080/graphql \
            --schema dgraph/schema.graphql \
            --name dgraph \
            --convert

      - name: Publish GraphQL schemas
        env:
          APOLLO_KEY: ${{ secrets.TICKETING_GATEWAY_KEY }}
        run: |
          npx -p @apollo/rover \
            rover subgraph publish ticketing-gateway \
            --routing-url http://tickets-srv:4001/graphql \
            --schema tickets/src/graphql/schema.graphql \
            --name tickets \
            --convert
          npx -p @apollo/rover \
            rover subgraph publish ticketing-gateway \
            --routing-url http://orders-srv:4002/graphql \
            --schema orders/src/graphql/schema.graphql \
            --name orders \
            --convert
          npx -p @apollo/rover \
            rover subgraph publish ticketing-gateway \
            --routing-url http://payments-srv:4003/graphql \
            --schema payments/src/graphql/schema.graphql \
            --name payments \
            --convert