name: preview

on: workflow_dispatch

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: Login
        uses: okteto/login@master
        with:
          token: ${{ secrets.OKTETO_TOKEN }}

      - name: Activate Namespace
        uses: okteto/namespace@master
        with:
          name: kch-chiu

      - name: Trigger the pipeline
        uses: okteto/pipeline@master
        with:
          timeout: 10m

      - name: Install Rover
        run: |
          curl -ssL https://rover.apollo.dev/nix/v0.1.0 | sh
          echo "$HOME/.rover/bin" >> $GITHUB_PATH

      - name: Publish GraphQL Dgraph schemas
        env:
          APOLLO_KEY: ${{ secrets.TICKETING_GATEWAY_DGRAPH_KEY }}
        run: |
          rover subgraph publish ticketing-gateway \
            --routing-url http://tickets-dgraph-srv:8080/graphql \
            --schema tickets/src/dgraph/schema.graphql \
            --name tickets-dgraph \
            --convert
          rover subgraph publish ticketing-gateway \
            --routing-url http://orders-dgraph-srv:8080/graphql \
            --schema orders/src/dgraph/schema.graphql \
            --name orders-dgraph \
            --convert

      - name: Publish GraphQL schemas
        env:
          APOLLO_KEY: ${{ secrets.TICKETING_GATEWAY_KEY }}
        run: |
          rover subgraph publish ticketing-gateway-dgraph \
            --routing-url http://tickets-srv:4001/graphql \
            --schema tickets/src/graphql/schema.graphql \
            --name tickets \
            --convert
          rover subgraph publish ticketing-gateway-dgraph \
            --routing-url http://orders-srv:4002/graphql \
            --schema orders/src/graphql/schema.graphql \
            --name orders \
            --convert