name: preview

on:
  pull_request:
    branches:
      - master

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master

    - name: Change to auth service
      run: cd auth

    - name: Setup Node for auth
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        registry-url: 'https://npm.pkg.github.com'

    - name: Change to expiration service
      run: cd ../expiration
      
    - name: Setup Node for expiration
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        registry-url: 'https://npm.pkg.github.com'

    - name: Change to tickets service
      run: cd ../tickets

    - name: Setup Node for tickets
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        registry-url: 'https://npm.pkg.github.com'

    - name: Change to orders service
      run: cd ../orders

    - name: Setup Node for orders
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        registry-url: 'https://npm.pkg.github.com'

    - name: Change to payments service
      run: cd ../payments

    - name: Setup Node for payments
      uses: actions/setup-node@v1
      with:
        node_version: '12.x'
        registry-url: 'https://npm.pkg.github.com'

    - name: Change to project directory
      run: cd ..

    - name: Login
      uses: okteto/login@master
      with:
        token: ${{ secrets.OKTETO_TOKEN }}

    - name: Trigger the pipeline
      uses: okteto/pipeline@master
      with: 
        namespace: kch-chiu
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}