name: preview

on: workflow_dispatch

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache tickets image layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-tickets-cache
          key: ${{ runner.os }}-buildx-tickets-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-tickets

      - name: Cache orders image layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-orders-cache
          key: ${{ runner.os }}-buildx-orders-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-orders
      
      - name: Cache payments image layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-payments-cache
          key: ${{ runner.os }}-buildx-payments-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-payments
      
      - name: Cache gateway image layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-gateway-cache
          key: ${{ runner.os }}-buildx-gateway-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-gateway

      - name: Cache gateway-dgraph image layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-gateway-dgraph-cache
          key: ${{ runner.os }}-buildx-gateway-dgraph-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-gateway-dgraph

      - name: Login to Okteto Registry
        uses: docker/login-action@v1
        with:
          registry: registry.cloud.okteto.net
          username: kch-chiu
          password: ${{ secrets.OKTETO_TOKEN }}

      - name: Build and push tickets
        uses: docker/build-push-action@v2
        with:
          context: tickets
          file: tickets/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          build-args: NODE_AUTH_TOKEN=${{ github.token }}
          push: true
          tags: registry.cloud.okteto.net/kch-chiu/tickets:${{ github.sha }}
          cache-from: type=local,src=/tmp/.buildx-tickets-cache
          cache-to: type=local,dest=/tmp/.buildx-tickets-cache
        
      - name: Build and push orders
        uses: docker/build-push-action@v2
        with:
          context: orders
          file: orders/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          build-args: NODE_AUTH_TOKEN=${{ github.token }}
          push: true
          tags: registry.cloud.okteto.net/kch-chiu/orders:${{ github.sha }}
          cache-from: type=local,src=/tmp/.buildx-orders-cache
          cache-to: type=local,dest=/tmp/.buildx-orders-cache

      - name: Build and push payments
        uses: docker/build-push-action@v2
        with:
          context: payments
          file: payments/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          build-args: NODE_AUTH_TOKEN=${{ github.token }}
          push: true
          tags: registry.cloud.okteto.net/kch-chiu/payments:${{ github.sha }}
          cache-from: type=local,src=/tmp/.buildx-payments-cache
          cache-to: type=local,dest=/tmp/.buildx-payments-cache

      - name: Build and push gateway
        uses: docker/build-push-action@v2
        with:
          context: gateway
          file: gateway/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          build-args: NODE_AUTH_TOKEN=${{ github.token }}
          push: true
          tags: registry.cloud.okteto.net/kch-chiu/gateway:${{ github.sha }}
          cache-from: type=local,src=/tmp/.buildx-gateway-cache
          cache-to: type=local,dest=/tmp/.buildx-gateway-cache

      - name: Build and push gateway-dgraph
        uses: docker/build-push-action@v2
        with:
          context: gateway-dgraph
          file: gateway-dgraph/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          build-args: NODE_AUTH_TOKEN=${{ github.token }}
          push: true
          tags: registry.cloud.okteto.net/kch-chiu/gateway-dgraph:${{ github.sha }}
          cache-from: type=local,src=/tmp/.buildx-gateway-dgraph-cache
          cache-to: type=local,dest=/tmp/.buildx-gateway-dgraph-cache

      - name: Login to Okteto Cloud
        uses: okteto/login@master
        with:
          token: ${{ secrets.OKTETO_TOKEN }}

      - name: Activate Namespace
        uses: okteto/namespace@master
        with:
          namespace: kch-chiu

      - name: Trigger the pipeline
        uses: okteto/pipeline@master
        with:
          name: ${{ github.workflow }}
          timeout: 10m

      - name: Publish GraphQL Dgraph schema
        env:
          APOLLO_KEY: ${{ secrets.TICKETING_GATEWAY_DGRAPH_KEY }}
        run: |
          npx -p @apollo/rover \
            rover subgraph publish ticketing-gateway-dgraph-ex1l5e \
            --routing-url http://dgraph-srv:8080/graphql \
            --schema dgraph/schema.graphql \
            --name dgraph \
            --convert

      - name: Publish GraphQL API schemas
        env:
          APOLLO_KEY: ${{ secrets.TICKETING_GATEWAY_KEY }}
        run: |
          npx -p @apollo/rover \
            rover subgraph publish ticketing-gateway \
            --routing-url http://tickets-srv:4001/graphql \
            --schema tickets/src/graphql/schema.graphql \
            --name tickets \
            --convert
          npx -p @apollo/rover \
            rover subgraph publish ticketing-gateway \
            --routing-url http://orders-srv:4002/graphql \
            --schema orders/src/graphql/schema.graphql \
            --name orders \
            --convert
          npx -p @apollo/rover \
            rover subgraph publish ticketing-gateway \
            --routing-url http://payments-srv:4003/graphql \
            --schema payments/src/graphql/schema.graphql \
            --name payments \
            --convert