name: preview

on: workflow_dispatch

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: Login to Okteto Cloud
        uses: okteto/context@latest
        with:
          token: ${{ secrets.OKTETO_TOKEN }}
          namespace: kch-chiu

      - name: Build and push tickets
        uses: okteto/build@latest
        env:
          NODE_AUTH_TOKEN: ${{ github.token }}
        with:
          tag: okteto.dev/tickets:${{ github.sha }}
          path: tickets
          buildargs: NODE_AUTH_TOKEN

      - name: Build and push orders
        uses: okteto/build@latest
        env:
          NODE_AUTH_TOKEN: ${{ github.token }}
        with:
          tag: okteto.dev/orders:${{ github.sha }}
          path: orders
          buildargs: NODE_AUTH_TOKEN
          
      - name: Build and push payments
        uses: okteto/build@latest
        env:
          NODE_AUTH_TOKEN: ${{ github.token }}
        with:
          tag: okteto.dev/payments:${{ github.sha }}
          path: payments
          buildargs: NODE_AUTH_TOKEN

      - name: Build and push gateway
        uses: okteto/build@latest
        env:
          NODE_AUTH_TOKEN: ${{ github.token }}
        with:
          tag: okteto.dev/gateway:${{ github.sha }}
          path: gateway
          buildargs: NODE_AUTH_TOKEN

      - name: Build and push gateway-dgraph
        uses: okteto/build@latest
        env:
          NODE_AUTH_TOKEN: ${{ github.token }}
        with:
          tag: okteto.dev/gateway-dgraph:${{ github.sha }}
          path: gateway-dgraph
          buildargs: NODE_AUTH_TOKEN

      - name: Trigger the pipeline
        uses: okteto/pipeline@master
        with:
          name: ${{ github.workflow }}
          timeout: 10m

      - name: Publish GraphQL Dgraph schema
        env:
          APOLLO_KEY: ${{ secrets.TICKETING_GATEWAY_DGRAPH_KEY }}
        run: |
          npx -p @apollo/rover \
            rover subgraph publish ticketing-gateway-dgraph-ex1l5e \
            --routing-url http://dgraph-srv:8080/graphql \
            --schema dgraph/schema.graphql \
            --name dgraph \
            --convert

      - name: Publish GraphQL API schemas
        env:
          APOLLO_KEY: ${{ secrets.TICKETING_GATEWAY_KEY }}
        run: |
          npx -p @apollo/rover \
            rover subgraph publish ticketing-gateway \
            --routing-url http://tickets-srv:4001/graphql \
            --schema tickets/src/graphql/schema.graphql \
            --name tickets \
            --convert
          npx -p @apollo/rover \
            rover subgraph publish ticketing-gateway \
            --routing-url http://orders-srv:4002/graphql \
            --schema orders/src/graphql/schema.graphql \
            --name orders \
            --convert
          npx -p @apollo/rover \
            rover subgraph publish ticketing-gateway \
            --routing-url http://payments-srv:4003/graphql \
            --schema payments/src/graphql/schema.graphql \
            --name payments \
            --convert