name: preview

on: workflow_dispatch

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: Login
        uses: okteto/login@master
        with:
          token: ${{ secrets.OKTETO_TOKEN }}

      - name: Activate Namespace
        uses: okteto/namespace@master
        with:
          name: kch-chiu

      - name: Trigger the pipeline
        uses: okteto/pipeline@master
        with:
          timeout: 10m

      - name: Register GraphQL Dgraph and API schemas
        env:
          APOLLO_KEY: ${{ secrets.APOLLO_KEY }}
        run: |
          npx apollo service:push \
            --graph=gateway-ticketing-dgraph-y0c4 \
            --serviceName=tickets-dgraph \
            --serviceURL=http://tickets-dgraph-srv:8080/graphql \
            --localSchemaFile=tickets/src/dgraph/dgraph-schema.graphql
          npx apollo service:push \
            --graph=gateway-ticketing-dgraph-y0c4 \
            --serviceName=orders-dgraph \
            --serviceURL=http://orders-dgraph-srv:8080/graphql \
            --localSchemaFile=orders/src/dgraph/dgraph-schema.graphql
          npx apollo service:push \
            --graph=gateway-ticketing-client \
            --serviceName=tickets \
            --serviceURL=http://tickets-srv:4001/graphql \
            --localSchemaFile=tickets/src/graphql/schema.graphql
          npx apollo service:push \
            --graph=gateway-ticketing-client \
            --serviceName=orders \
            --serviceURL=http://orders-srv:4002/graphql \
            --localSchemaFile=orders/src/graphql/schema.graphql