name: preview

on:
  pull_request:
    branches:
      - master

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master

    - name: Setup Node for auth
      run: cd auth
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        registry-url: 'https://npm.pkg.github.com'

    - name: Setup Node for expiration
      run: cd expiration
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        registry-url: 'https://npm.pkg.github.com'

    - name: Setup Node for tickets
      run: cd tickets
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        registry-url: 'https://npm.pkg.github.com'

    - name: Setup Node for orders
      run: cd orders
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        registry-url: 'https://npm.pkg.github.com'

    - name: Setup Node for payments
      run: cd payments
      uses: actions/setup-node@v1
      with:
        node_version: '12.x'
        registry-url: 'https://npm.pkg.github.com'

    - name: Login
      uses: okteto/login@master
      with:
        token: ${{ secrets.OKTETO_TOKEN }}

    - name: Trigger the pipeline
      uses: okteto/pipeline@master
      with: 
        namespace: kch-chiu
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}