name: tests-orders

on:
  pull_request:
    paths:
      - 'orders/**'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: 'Setup node for orders service'
        shell: bash
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
        run: |
          echo //npm.pkg.github.com/:_authToken="$NODE_AUTH_TOKEN" >> orders/.npmrc
          echo @kch-chiu:registry=https://npm.pkg.github.com >> orders/.npmrc
          echo always-auth=true >> orders/.npmrc
      - name: 'Run tests for orders service'  
        run: |
          cd orders
          npm ci
          rm -f .npmrc
          npm run test:ci
        env:
          JWT_KEY: ${{ secrets.JWT_KEY }}