name: tests-auth

on:
  pull_request:
    paths:
      - 'auth/**'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout auth'
        uses: actions/checkout@master
      - name: 'Change to auth folder'
        run: cd auth
      - name: 'Authenticate to GitHub Package Registry'
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: '@kchiu-dev' 
      - name: 'Running tests for auth'
        run: npm install && npm run test:ci
        env:
          CI: true
          NODE_AUTH_TOKEN: ${{ secrets.CR_PAT }}