name: tests-orders

on:
  pull_request:
    paths:
      - 'orders/**'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Running tests for orders'
        uses: actions/checkout@master
        with:
          submodules: true
      - run: cd common && npm install
      - run: cd orders && npm install && npm run test:ci
