name: tests-auth

on:
  pull_request:
    paths:
      - 'auth/**'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: 'Setup node and run tests for auth service'
        shell: bash
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
        run: |
          echo '//npm.pkg.github.com/:_authToken="$NODE_AUTH_TOKEN"\n'\
          '@kch-chiu:registry:https://npm.pkg.github.com\n'\
          'always-auth=true' >> auth/.npmrc
          cat auth/.npmrc