name: tests-orders

on:
  pull_request:
    paths:
      - 'orders/**'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: 'Setup Node for orders'
        shell: bash
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
        run: |
          echo '//npm.pkg.github.com/:_authToken=${NODE_AUTH_TOKEN}\n'\
          '@kch-chiu:registry=https://npm.pkg.github.com\n'\
          'always-auth=true' >> orders/.npmrc
      - name: 'Running tests for orders service'
        run: cd orders && npm ci && rm -f .npmrc && npm run test:ci