name: tests-payments

on:
  pull_request:
    paths:
      - 'payments/**'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Running tests for payments'
        uses: actions/checkout@master
      - run: cd payments && npm install && npm run test:ci
