name: tests-auth

on:
  pull_request:
    paths:
      - 'auth/**'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: 'Setup Node for auth'
        run: echo "//npm.pkg.github.com/:_authToken=$NODE_AUTH_TOKEN" >> auth/.npmrc
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
      - name: 'Running tests for auth service'
        run: cd auth && npm ci && npm run test:ci