name: tests-auth

on:
  pull_request:
    paths:
      - 'auth/**'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Running tests for auth'
        uses: actions/checkout@master
        with:
          submodules: true
      - run: cd auth && npm install && npm run test:ci
         
