name: tests-orders

on:
  pull_request:
    paths:
      - 'orders/**'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Running tests for orders'
        uses: actions/checkout@master
      - name: 'Authenticate to GitHub Package Registry'
        run: npm set //npm.pkg.github.com/:_authToken ${{ secrets.CR_PAT }}
      - run: cd orders && npm install && npm run test:ci
