name: tests-tickets

on:
  pull_request:
    paths:
      - 'tickets/**'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Running tests for tickets'
        uses: actions/checkout@master
        with:
          submodules: true
      - run: cd tickets && npm install && npm run test:ci
