name: tests-auth

on:
  pull_request:
    paths:
      - 'auth/**'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: 'Setup Node'
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@kch-chiu'
      - name: 'Running tests for auth service'
        run: cd auth && npm install && npm run test:ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_PAT }}