name: tests-orders

on:
  pull_request:
    paths:
      - 'orders/**'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: 'Setup Node for orders'
        run: echo "//npm.pkg.github.com/:_authToken=$NODE_AUTH_TOKEN" >> orders/.npmrc
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
      - name: 'Running tests for orders service'
        run: cd orders && npm ci && npm run test:ci