name: tests-payments

on:
  pull_request:
    paths:
      - 'payments/**'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Running tests for payments'
        uses: actions/checkout@master
      - name: 'Authenticate to GitHub Package Registry'
        run: npm set //npm.pkg.github.com/:_authToken ${{ secrets.CR_PAT }}
      - run: cd payments && npm install && npm run test:ci
