name: tests-auth

on:
  pull_request:
    paths:
      - 'auth/**'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout auth'
        uses: actions/checkout@master
      - name: 'Login to GitHub Package Registry'
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.CR_PAT }}" > ~/.npmrc
          cd auth
          npm config set registry https://npm.pkg.github.com/kchiu-dev
      - name: 'Running tests for auth'
        run: npm install && npm run test:ci
         