name: tests-tickets

on:
  pull_request:
    paths:
      - 'tickets/**'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: 'Setup node for tickets service'
        shell: bash
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
        run: |
          echo //npm.pkg.github.com/:_authToken="$NODE_AUTH_TOKEN" >> tickets/.npmrc
          echo @kch-chiu:registry=https://npm.pkg.github.com >> tickets/.npmrc
          echo always-auth=true >> tickets/.npmrc
      - name: 'Run tests for tickets service'
        run: |
          cd tickets
          npm ci
          rm -f .npmrc
          npm run test:ci
        env:
          JWT_KEY: ${{ secrets.JWT_KEY }}